### ISSUE TITLE
test.py doesnot output any meaningful result?  the code is not finished?

### ISSUE THREAD

**Issue by asa008** [khalooei/ALOCC-CVPR2018#11]
test.py doesnot output any meaningful result? the code is not finished?  how about AUC?

**Comment by AshleyYang25** [comment]
I also encountered this problem, hope the author answer as soon as possible

**Comment by MyronXie** [comment]
I have the same problem too. I can't find the relationship between `results_d` mentioned in test.py and `D(R(X))` mentioned in the paper. Hope the author will see this issue asap.

**Comment by khalooei** [comment]
Dear @asa008 @AshleyYang25 @MyronXie ; At that time, I didn't have much time to publish the full fresh public source code. By the way, I tried to release a public fresh code of our implementation for the initialization step for anyone who wants to use this approach for their productions (this is just the guidance to beginners). So, If you follow our public publishment of that version, you can find that we use the f_test_frozen_model function in model.py which wants to get the values of each patch when we want to determine the inlier class. As you can see, when we feed the raw data to the discriminator, we could just run our self.D_logits node of the ALOCC computational graph and when we want to get the generated ones, we can run self.G node. You can find that result_d means the output vector of their corresponded probabilities of input batch, which could detect that our input batch is inlier or outlier simultaneously.
