### ISSUE TITLE
confusion about Discriminator

### ISSUE THREAD

**Issue by Goody7** [khalooei/ALOCC-CVPR2018#14]
In my experiment, the output of the discriminator is about 0.49 after GAN convergence. How could you make the discriminator output probability larger than 0.5?

**Comment by cod3r0k** [comment]
> 
> 
> In my experiment, the output of the discriminator is about 0.49 after GAN convergence. How could you make the discriminator output probability larger than 0.5?

As I mentioned [before](https://github.com/khalooei/ALOCC-CVPR2018/issues/15#issuecomment-508860539)
I hope the authors answer these questions as soon as possible, but I had the same problem with your mentioned issue, but it depends on our training stop. The GAN training with pure optimization scenarios, has some tricks for stopping criteria.

**Comment by khalooei** [comment]
> In my experiment, the output of the discriminator is about 0.49 after GAN convergence. How could you make the discriminator output probability larger than 0.5?



> > In my experiment, the output of the discriminator is about 0.49 after GAN convergence. How could you make the discriminator output probability larger than 0.5?
> 
> As I mentioned [before](https://github.com/khalooei/ALOCC-CVPR2018/issues/15#issuecomment-508860539)
> I hope the authors answer these questions as soon as possible, but I had the same problem with your mentioned issue, but it depends on our training stop. The GAN training with pure optimization scenarios, has some tricks for stopping criteria.

Dear @Goody7 and @cod3r0k , As you know, the GANs are difficult to train. The reason they are difficult to train is that both the generator model and the discriminator model are trained simultaneously in a game. This means that improvements to one model come at the expense of the other model (In our case, we have `R` as generator model and `D` as reference discriminator model). The goal of training two models involves finding a point of equilibrium between the two competing concerns and as we mentioned in our paper, it depends on our stopping criteria over the time and status of each network.
