### ISSUE TITLE
Discriminator Output Confusion

### ISSUE THREAD

**Issue by lingyi-Yue** [khalooei/ALOCC-CVPR2018#15]
Is the output of the discriminator an anomaly score during the test of anomaly detection? Why is the output of the discriminator a very small value when I am testing, on the order of e-9 to e-20?

**Comment by tiandamiao** [comment]
I have the same problem. Have you solved it?

**Comment by cod3r0k** [comment]
> 
> 
> Is the output of the discriminator an anomaly score during the test of anomaly detection? Why is the output of the discriminator a very small value when I am testing, on the order of e-9 to e-20?

Of course, yes. I hope the authors answer these questions as soon as possible, but I had the same problem with your mentioned issue, but it depends on our training stop. The GAN training with pure optimization scenarios, has some tricks for stopping criteria. Their idea and implementation was very well. Also, you can find the Adversarial AutoEncoder ALOCC (`Generative Probabilistic Novelty Detection with Adversarial Autoencoders`) which was the same as pure ALOCC.

**Comment by khalooei** [comment]
> Is the output of the discriminator an anomaly score during the test of anomaly detection? Why is the output of the discriminator a very small value when I am testing, on the order of e-9 to e-20?



> I have the same problem. Have you solved it?



> > Is the output of the discriminator an anomaly score during the test of anomaly detection? Why is the output of the discriminator a very small value when I am testing, on the order of e-9 to e-20?
> 
> Of course, yes. I hope the authors answer these questions as soon as possible, but I had the same problem with your mentioned issue, but it depends on our training stop. The GAN training with pure optimization scenarios, has some tricks for stopping criteria. Their idea and implementation was very well. Also, you can find the Adversarial AutoEncoder ALOCC (`Generative Probabilistic Novelty Detection with Adversarial Autoencoders`) which was the same as pure ALOCC.

Dear @lingyi-Yue @tiandamiao @cod3r0k , As I mentioned in #14, this depended on your configuration, stopping criteria and any other things which I previously answered in #14, #13, #5.
