### ISSUE TITLE
Will it works for fine grained multi-class novelty detection?

### ISSUE THREAD

**Issue by asdfqwer2015** [khalooei/ALOCC-CVPR2018#17]
Hi, khalooei:
  Thanks for sharing your code, it's interesting.
  I've a little confusion about the model, could you please explain it?
  It seems the ALOCC can model generic single class(e.g. penguins) and `others` class(e.g. dogs, cats...) very well.
  Will it works for these scenarios?
  a. generic `train-set multi-classes` class and `others` class? i.e. R models a distribution for not only one explicit class but a complex distribution for all classes in train-set
  b. for fine-grained dataset, one explicit class as base class and others as novelty classes? i.e. base class and novelty class may have more similar distributions than generic class dataset
  c. fine-grained multi-classes as base class and others as novelty class?
  Thanks.

**Comment by khalooei** [comment]
Dear @asdfqwer2015 , Thank you for your comments. I'm so sorry for late reply and don't hesitate to mail me (or my colleagues) for faster reply. Our goal focused on one class classification task, but you can extend it in different approaches. One of them could be the conditional case of ALOCC which you can feed different constraints which you can guide the specific goal. Also, I think you can do it with a similar probabilistic fusion operation which condition one-class to multi-class over a time. Another one would be the idea which you use ensemble approach and each network, which participate in ensemble approach is specialized in one-class task. Also, you can use extended learning as a knowledge distillation approach to pay more attention in class adding phases.
