### ISSUE TITLE
frame_patches = nd_patch.transpose([1,0,2,3])

### ISSUE THREAD

**Issue by husnejahan** [khalooei/ALOCC-CVPR2018#23]
getting error for UCSD dataset:
File "test.py", line 168, in process_frame
    frame_patches = nd_patch.transpose([1,0,2,3])
ValueError: axes don't match array

**Comment by khalooei** [comment]
Dear @husnejahan , Please check your input preparation. 
Don't hesitate to contact me if you need any help.
