### ISSUE TITLE
Collaborations with your team in extending new idea

### ISSUE THREAD

**Issue by cod3r0k** [khalooei/ALOCC-CVPR2018#7]
Hi there, I want to extend your idea for adversarial training. Is there anyone which has time for helping me to use it for that purpose?

**Comment by Sabokrou** [comment]
Dear @cod3r0k 
Thank you for your interesting.  Please send a message to me. "sabokro@gmail.com"

**Comment by Sabokrou** [comment]
Dear cod3rok,
You can send an email to me: sabokro@gmail.com

**Comment by cod3r0k** [comment]
> 
> 
> Dear cod3rok,
> You can send an email to me: [sabokro@gmail.com](mailto:sabokro@gmail.com)

Happy New year! Thank you! I'll get back to you as soon as possible.
