### ISSUE TITLE
Frame-level scores of your experiment on Ped2?

### ISSUE THREAD

**Issue by nguyetn89** [khalooei/ALOCC-CVPR2018#9]
Hi Sabokrou,

Thank you for the source code of this good work!
I would like to explore more about your approach. Could you please provide the frame-level scores of Ped2 you obtained in your experiment (which you used to estimate the EER in Table 2)?

Thank you!

**Comment by khalooei** [comment]
Dear @nguyetn89 , Your welcome, At that time, the ALOCC takes patches from each level and then feed each patch to the discriminator to achieve the results.
